[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; ---------- Upload / Debug ----------
; Pokud nahráváš přes ST-Link:
upload_protocol = stlink

; Pokud bys nahrával přes USB-serial bootloader, nech to zakomentované:
; upload_protocol = serial

; ---------- Serial monitor ----------
monitor_speed = 115200

; ---------- Libraries ----------
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306

; ---------- Build options ----------
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
